name: Reddit Daily STALKER Post

on:
  schedule:
    - cron: '0 8 * * *'  # 08:00 UTC = 10:00 CEST
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: git cloning
        uses: actions/checkout@v3

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: pythong requirements install
        run: pip install -r requirements.txt

      - name: .env
        run: |
          echo "REDDIT_CLIENT_ID=${{ secrets.REDDIT_CLIENT_ID }}" >> .env
          echo "REDDIT_CLIENT_SECRET=${{ secrets.REDDIT_CLIENT_SECRET }}" >> .env
          echo "REDDIT_USERNAME=${{ secrets.REDDIT_USERNAME }}" >> .env
          echo "REDDIT_PASSWORD=${{ secrets.REDDIT_PASSWORD }}" >> .env
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}  # Add this line

      - name: running script
        run: python main.py
